spring:
  datasource:
    url: jdbc:mysql://192.168.112.31:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: ENC(MT91y3hqb0x/p5qMHBIGkAHI5I6Y0ram)
    password: ENC(4N1tNOoY0zyuAfuiX1T26Ef4RvqDcY3AIHr7TBpbQ8w=)
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.106.76
    database: 6
    port: 6379
    password: ENC(kYjyUavJ/hWpppO1yvSIUotbAn2MeeOu)

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  type-aliases-package: com.xxx.mall.mapper
#  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
