# mysql and tk.mybatis
spring:
  datasource:
    url: jdbc:mysql://192.168.112.31:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: eCityArcTest
    password: rickControl@test
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
  redis:
    host: 192.168.106.76
    database: 6
    port: 6379
    password: Hello1234
